---
title: 'Plots and Tables for EDM'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r data}
# d <- targets::tar_read("d_analysis")
d <- readRDS(here::here("data", "d_analysis.rds"))
```

# Plots

```{r subsets}
## Subsets
chat <- d %>%
  filter(is_chat)

twlz <- d %>%
  filter(is_twlz)
```


```{r color}
## Color
# - https://ggplot2-book.org/scale-colour.html?q=color%20blind#colour-blindness
# - https://www.vischeck.com/

colorBlindness::displayAllColors(viridis::viridis(6))
colorBlindness::displayAllColors(c("#E64B35FF", "#3C5488FF"))
colorBlindness::displayAllColors(c("#DC0000FF", "#22A884FF"))
```

## Time-series - Users
```{r}
chat_stat_users <- chat %>%
  group_by(year) %>%
  summarise(
    n_users = user_id %>% n_distinct()
  ) %>%
  mutate(community = "EdChatDE") %>%
  add_row(year = "2012", n_users = 0, community = "EdChatDE") %>%
  add_row(year = "2011", n_users = 0, community = "EdChatDE") %>%
  arrange(year)

twlz_stat_users <- twlz %>%
  group_by(year) %>%
  summarise(
    n_users = user_id %>% n_distinct()
  ) %>%
  mutate(community = "TWLZ") %>%
  add_row(year = "2007", n_users = 0, community = "TWLZ") %>%
  add_row(year = "2006", n_users = 0, community = "EdChatDE") %>%
  arrange(year)

time_stat_users <- bind_rows(chat_stat_users, twlz_stat_users)
time_stat_users <- time_stat_users %>%
  mutate(
    year = year %>% as.numeric()
  ) %>%
  arrange(year)
```


```{r}
year_labels <- as.character(seq(2004, 2022, 1))
year_labels[c(FALSE, TRUE)] <- ""

time_stat_users %>%
  ggplot(aes(x = year, y = n_users, color = community)) +
  geom_line() +
  scale_color_manual(values = c("#E64B35FF", "#3C5488FF")) +
  guides(color = FALSE) +
  scale_y_log10(
    breaks = scales::breaks_log(),
    labels = scales::label_log()
  ) +
  scale_x_continuous(
    limits = c(2006, 2022),
    breaks = seq(2004, 2022, 1),
    labels = year_labels
  ) +
  geom_label(label = "EdChatDE", x = 2012, y = log10(2000), color = "#E64B35FF") +
  geom_label(label = "TWLZ", x = 2009, y = log10(80), color = "#3C5488FF") +
  labs(y = expression(paste("Users ", (log[10])))) +
  papaja::theme_apa(box = TRUE) +
  theme(
    axis.title.y = element_text(margin = margin(r = 3, unit = "pt")),
    axis.title.x = element_blank()
  )

ggsave(filename = "log_users.png", height = 4, width = 6)
```


## Jitter Mosaic
```{r gradients}
doi <- c("innovators", "early adopters", "early majority", "late majority", "laggards")

d_user_groups <- d %>%
  distinct(user_id, .keep_all = TRUE) %>%
  select(twlz_member_group, edchatde_member_group) %>%
  na.omit() %>%
  mutate(group = str_glue("{twlz_member_group}|{edchatde_member_group}")) %>%
  mutate(
    edchatde_member_group_f = factor(edchatde_member_group, level = doi),
    twlz_member_group_f = factor(twlz_member_group, level = doi)
  )

# residuals from chi-square expected frequencies assuming independence
gradients <- readRDS(here::here("data", "gradients.rds"))

gradients <- gradients %>%
  mutate(group = str_glue("{twlz_member_group}|{edchatde_member_group}")) %>%
  select(group, Freq)

d_user_groups <- d_user_groups %>%
  left_join(gradients, by = c("group" = "group"))
```


```{r}
d_user_groups %>%
  ggplot(aes(x = twlz_member_group_f, y = edchatde_member_group_f, color = Freq)) +
  geom_jitter() +
  scale_color_viridis_c(name = "", breaks = seq(-6, 6, 3)) +
  scale_x_discrete(labels = scales::wrap_format(10)) +
  scale_y_discrete(labels = scales::wrap_format(10)) +
  labs(x = "TWLZ Member Group", y = "#EdChatDE Member Group") +
  coord_fixed() +
  papaja::theme_apa(box = TRUE) +
  theme(axis.title.y = element_text(margin = margin(r = 3, unit = "pt"))) +
  theme(
    legend.position = "right",
    legend.margin = margin(l = -3, unit = "pt"),
    legend.text = element_text(margin = margin(l = -2.5, unit = "pt"))
  )

ggsave(filename = "group_jitter_freq.png", height = 4.5, width = 5.5)
```


## Timing boxplot - Teachers
```{r switch stats}
d_user_switch <- d %>%
  select(
    user_id, user_switched, user_switch_time, edchatde_member_group,
    is_teacher
  ) %>%
  filter(!is.na(user_switched)) %>%
  filter(!is.na(user_switch_time)) %>%
  distinct(user_id, .keep_all = TRUE) %>%
  arrange(desc(user_switched))

# Standardize time to unix time, then Z standardize
d_user_switch["user_switch_time_standard"] <- d_user_switch$user_switch_time %>%
  as.POSIXct(format = "%Y-%m-%dT%H:%M:%OS", tz = "UTC") %>%
  as.numeric() %>%
  scale()

d_user_switch <- d_user_switch %>%
  mutate(
    edchatde_member_group_f = factor(edchatde_member_group,
      level = c("innovators", "early adopters", "early majority", "late majority", "laggards")
    ),
    is_teacher = is_teacher %>% factor(
      levels = c("TRUE", "FALSE"),
      labels = c("Teacher", "Non-Teacher")
    )
  )
```

```{r boxplot}
d_user_switch$user_switch_time_standard %>% summary()

d_user_switch %>%
  ggplot(aes(
    x = edchatde_member_group_f,
    y = user_switch_time_standard,
    fill = is_teacher
  )) +
  scale_x_discrete(labels = scales::wrap_format(10)) +
  scale_y_continuous(limits = c(-4.15, 2.5), breaks = seq(-4, 2, 2)) +
  geom_boxplot(position = position_dodge2(0.75, preserve = "single")) + # center and keep same size individually
  scale_fill_manual(
    name = "",
    values = c("#DC0000FF", "#22A884FF")
  ) +
  labs(x = "#EdChatDE Member Group", y = "User Switch Time") +
  papaja::theme_apa(box = TRUE) +
  theme(legend.position = "top") +
  theme(
    legend.margin = margin(b = -7, unit = "pt"),
    axis.title.y = element_text(margin = margin(r = 3, unit = "pt"))
  )

ggsave(filename = "switch_explain_teachers.png", height = 4, width = 6)
```


# Regression Models

## User switch time - Linear regression
```{r}
user_stats <- d %>%
  group_by(user_id) %>%
  summarise(
    user_repost_count = sum(retweet_count) + sum(quote_count)
  ) %>%
  select(user_id, user_repost_count)

d_users <- d %>%
  filter(!is.na(user_switched)) %>%
  arrange(desc(user_switch_time)) %>%
  distinct(user_id, .keep_all = TRUE) %>%
  filter(!is.na(user_switch_time)) %>%
  left_join(user_stats, by = "user_id")

var_space <- c(
  "user_switch_time",
  "edchatde_member_group",
  "is_teacher",
  "n_interactions_edchat",
  "user_lifespan_days",
  "user_following_count",
  "user_followers_count",
  "n_tweets_edchat_per_day",
  "user_repost_count",
  "centrality_degree",
  "centrality_closeness",
  "centrality_betweenness",
  "centrality_eigen"
)

d_model <- d_users %>%
  select(!!var_space) %>%
  mutate_if(is.numeric, ~ replace(., is.na(.), 0)) %>%
  drop_na()

# Log centralities
d_model$centrality_degree <- d_model$centrality_degree %>% log()
d_model$centrality_closeness <- d_model$centrality_closeness %>% log()
d_model$centrality_betweenness <- d_model$centrality_betweenness %>% log()
d_model$centrality_eigen <- d_model$centrality_eigen %>% log()

d_model$centrality_degree[is.infinite(d_model$centrality_degree)] <- 0
d_model$centrality_betweenness[is.infinite(d_model$centrality_betweenness)] <- 0
d_model$centrality_eigen[is.infinite(d_model$centrality_eigen)] <- 0
d_model$centrality_closeness[is.infinite(d_model$centrality_closeness)] <- 0

# Standardize predictors to ease interpretation
d_model <- d_model %>%
  mutate_if(is.numeric, scale)

# Standardize time to unix time, then Z standardize
d_model["user_switch_time_standard"] <- d_model$user_switch_time %>%
  as.POSIXct(format = "%Y-%m-%dT%H:%M:%OS", tz = "UTC") %>%
  as.numeric() %>%
  scale()

d_model$edchatde_member_group <- d_model$edchatde_member_group %>%
  factor(levels = c("innovators", "early adopters", "early majority", "late majority", "laggards"))

d_model <- d_model %>%
  select(-user_switch_time)

# Fit + Search
m <- lm(user_switch_time_standard ~ ., d_model)
summary(m)

mm <- MASS::stepAIC(m, direction = "backward")
summary(mm)

sjPlot::tab_model(mm)
```


## Print model
```{r}
mm_stats <- mm %>%
  broom::tidy() %>%
  select(term, estimate, std.error, p.value) %>%
  add_row(.before = 1, term = "EdChatDE DOI group") %>%
  mutate(
    stars = symnum(p.value, corr = FALSE, na = FALSE, cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")),
    p.value = scales::pvalue(p.value),
    estimate = estimate %>% round(digits = 2),
    estimate_print = paste0(estimate, stars)
  ) %>%
  select(term, estimate_print, std.error)

# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# Export booktabs tabular
mm_stats %>%
  kableExtra::kbl(
    format = "latex",
    booktabs = TRUE,
    col.names = c("Effect", "Estimate", "SE"),
    digits = c(0, 0, 2)
  ) %>%
  clipr::write_clip()
```


## User switch - Logistic regression
```{r logistic}
d_users_log <- d %>%
  filter(!is.na(user_switched)) %>%
  arrange(desc(user_switched)) %>%
  distinct(user_id, .keep_all = TRUE)

var_space_log <- c(
  "user_switched",
  "edchatde_member_group",
  "n_interactions_edchat",
  "user_lifespan_days",
  "user_following_count",
  "user_followers_count",
  "n_tweets_edchat_per_day",
  "is_teacher",
  "centrality_degree",
  "centrality_closeness",
  "centrality_betweenness",
  "centrality_eigen"
)

d_model <- d_users_log %>%
  select(!!var_space_log) %>%
  mutate_if(is.numeric, ~ replace(., is.na(.), 0)) %>%
  drop_na()

# Log centralities
d_model$centrality_degree <- d_model$centrality_degree %>% log()
d_model$centrality_closeness <- d_model$centrality_closeness %>% log()
d_model$centrality_betweenness <- d_model$centrality_betweenness %>% log()
d_model$centrality_eigen <- d_model$centrality_eigen %>% log()

d_model$centrality_degree[is.infinite(d_model$centrality_degree)] <- 0
d_model$centrality_betweenness[is.infinite(d_model$centrality_betweenness)] <- 0
d_model$centrality_eigen[is.infinite(d_model$centrality_eigen)] <- 0
d_model$centrality_closeness[is.infinite(d_model$centrality_closeness)] <- 0

# Standardize predictors to ease interpretation
d_model <- d_model %>%
  mutate(across(where(is.numeric), ~ .x %>%
    scale() %>%
    as.numeric()))

d_model$edchatde_member_group <- d_model$edchatde_member_group %>%
  factor(levels = c("innovators", "early adopters", "early majority", "late majority", "laggards"))

# Fit + Search
m_log <- glm(user_switched ~ ., d_model, family = "binomial")
summary(m_log)

log <- MASS::stepAIC(m_log, direction = "backward")
summary(log)

# plot(log)
# sjPlot::tab_model(log)
```

## Print Logistic Regression
```{r}
log_stats <- log %>%
  broom::tidy() %>%
  mutate(
    .after = "term",
    OR = exp(estimate) %>% round(digits = 2),
    std.error = std.error %>% round(digits = 2),
    stars = symnum(p.value, corr = FALSE, na = FALSE, cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")),
    OR_print = paste0(OR, stars)
  ) %>%
  select(term, OR_print, std.error)

# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

log_stats %>%
  kableExtra::kbl(
    format = "latex",
    booktabs = TRUE,
    col.names = c("Effect", "OR", "SE"),
    digits = c(0, 0, 2)
  ) %>%
  clipr::write_clip()
```
